### ISSUE TITLE
Product Single: There's a new design "06A-BEN-products-single.psd" for products single. Is this an approved design? If yes, kindly update the scope accordingly.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Benchmark-Systems#3]
![image](https://cloud.githubusercontent.com/assets/12888048/16442980/9c097b4c-3e08-11e6-9acc-295e8892e970.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16442982/9e82d594-3e08-11e6-94e4-d4bef3ed2e86.png)

**Comment by judetitan** [comment]
product title is placed on h1 tag and removed right above the description to avoid redundant h1 title "Product"
