### ISSUE TITLE
Homepage - Brands: Responsive error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Benchmark-Systems#56]
**There's no space between the brand image and arrow
768px - 991px
320px - 400px**
![image](https://cloud.githubusercontent.com/assets/12888048/16482221/618a8b26-3ee1-11e6-99d7-664adabaa4f1.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16482222/61ddd07e-3ee1-11e6-8379-df6ab0f5d648.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16482230/6ad2718a-3ee1-11e6-8962-596eff06cb96.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16482236/6e56c0d6-3ee1-11e6-90fd-7b8d1440a212.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16482239/70b29030-3ee1-11e6-906e-92409dc72a42.png)

**Comment by judetitan** [comment]
Removed the arrows on mobile devices

**Comment by romatitan** [comment]
**320px - 1199px** Resizing errors
![image](https://cloud.githubusercontent.com/assets/12888048/16795300/1f1523f4-490f-11e6-8df8-68955b1aa6b8.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16795301/2065fc4c-490f-11e6-8e6d-b3120bbfddf4.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16795304/253f76ee-490f-11e6-9add-15f970595e59.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/16942687/0f020594-4dca-11e6-9f38-8e35c0475b1c.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16942689/1118c160-4dca-11e6-8750-d5c9db02c704.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/16944618/088715ec-4dd4-11e6-9090-61d7723cfef4.png)
