### ISSUE TITLE
Theme Options: Where did you use this "Read More" button?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Benchmark-Systems#8]
![image](https://cloud.githubusercontent.com/assets/12888048/16443177/d4a4ded2-3e09-11e6-9624-ff34edf4dbee.png)

**Comment by judetitan** [comment]
It hasn't been used so I will just remove it.

**Comment by romatitan** [comment]
@judetitan 
I'm sorry, I accidentally deleted your comment.
Kindly remove the "Read More" field if there's no use.
Thanks!
![image](https://cloud.githubusercontent.com/assets/12888048/16801026/e90b4ef2-492a-11e6-80b2-98401cf4c31a.png)
